name: umd_dining_refactor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  internet_connection_checker_plus: ^2.5.2
  hive: ^4.0.0-dev.2
  fpdart: ^1.1.0
  google_sign_in: ^6.2.1
  path_provider: ^2.1.4
  google_nav_bar: ^5.0.6
  flutter_moving_background: ^0.0.5
  url_launcher: ^6.3.1
  gif: ^2.3.0
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  animations: ^2.0.11
  numberpicker: ^2.1.2
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/